name: Publish nightly Version

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Get build date
      id: date
      run: echo "BUILD_DATE=$(date +'%Y-%m-%d %H:%M:%S %z')" >> $GITHUB_OUTPUT
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      env:
        VCS_REF: ${{ github.sha }}
        VERSION: nightly
        BUILD_DATE: ${{ steps.date.outputs.BUILD_DATE }}
      with:
        name: icyleafcn/hpr:nightly
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildargs: BUILD_DATE,VCS_REF,VERSION
    - name: Update Docker Hub Description
      uses: peter-evans/dockerhub-description@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: icyleafcn/hpr
